# Generated by Django 6.0.6 on 2026-06-23 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='cuenta_bloqueada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='intentos_fallidos',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
